// Case Studies
export const FETCH_CASESTUDIES_REQUEST = "FETCH_CASESTUDIES_REQUEST";
export const FETCH_CASESTUDIES_SUCCESS = "FETCH_CASESTUDIES_SUCCESS";
export const FETCH_CASESTUDIES_FAILURE = "FETCH_CASESTUDIES_FAILURE";
export const FETCH_CASESTUDIES_LIST_REQUEST = "FETCH_CASESTUDIES_LIST_REQUEST";
export const FETCH_CASESTUDIES_LIST_SUCCESS = "FETCH_CASESTUDIES_LIST_SUCCESS";
export const FETCH_CASESTUDIES_LIST_FAILURE = "FETCH_CASESTUDIES_LIST_FAILURE";

// Global loading (optional)
export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";
